spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/downpan
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8888
minio:
  endpoint: 172.28.43.29
  port: 9000
  accessKey: minio
  secretKey: miniopassword
  secure: false
  bucketName: "hope-bucket"
  configDir: "/home/data/"
jwt:
  expiration: 7200000
  token: Authorization
