spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/downpan?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8888
minio:
  endpoint: 127.0.0.1
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  secure: false
jwt:
  expiration: 7200000
  token: Authorization
downpan:
  fileServerRootUrl: http://192.168.0.103:8888/file/getFile/


